### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by phdru** [shaurz/fsmonitor#16]
Does the project work with Python 3? I got this error trying to run tests under Python 3.3 to 3.6:

```python
cd tests
python3.x test1.py
```

Error:

```
Traceback (most recent call last):
  File "test1.py", line 5, in <module>
    w = test.add_dir_watch(tempdir)
  File "/usr/local/src/Python/textern/fsmonitor/tests/test.py", line 21, in add_dir_watch
    return self.monitor.add_dir_watch(*args, **kwargs)
  File "/usr/local/src/Python/textern/fsmonitor/tests/../fsmonitor/__init__.py", line 45, in add_dir_watch
    return self.monitor.add_dir_watch(path, flags=flags, user=user, **kwargs)
  File "/usr/local/src/Python/textern/fsmonitor/tests/../fsmonitor/linux.py", line 140, in add_dir_watch
    return self._add_watch(path, flags, user, IN_ONLYDIR)
  File "/usr/local/src/Python/textern/fsmonitor/tests/../fsmonitor/linux.py", line 130, in _add_watch
    wd = inotify_add_watch(self.__fd, path, inotify_flags)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```

**Comment by ljmccarthy** [comment]
I originally wrote it for Python 2.x only since that was what I was still using at the time.

**Comment by phdru** [comment]
I'm working in the problem. It's caused by unicode — ctypes wants bytes and return bytes so I encode/decode to/from bytes. On Linux it works now with Python 3.3+. Gonna test with w32 and Python 3.5.
